module.exports = {
  // ===== USERS =====
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",
  USER_DEACTIVATE: "USER_DEACTIVATE",
  USER_VIEW: "USER_VIEW",

  // ===== ROLES & PERMISSIONS =====
  ROLE_MANAGE: "ROLE_MANAGE",
  PERMISSION_ASSIGN: "PERMISSION_ASSIGN",

  // ===== PROJECTS =====
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_EDIT: "PROJECT_EDIT",
  PROJECT_DELETE: "PROJECT_DELETE",
  PROJECT_VIEW: "PROJECT_VIEW",

  // ===== BOQ =====
  BOQ_CREATE: "BOQ_CREATE",
  BOQ_EDIT: "BOQ_EDIT",
  BOQ_DELETE: "BOQ_DELETE",

  // ===== APPROVALS =====
  APPROVAL_REVIEW: "APPROVAL_REVIEW",

  // ===== ACCOUNTING (future) =====
  ACCOUNT_CREATE: "ACCOUNT_CREATE",
  JOURNAL_POST: "JOURNAL_POST",
  INVOICE_CREATE: "INVOICE_CREATE",
  INVOICE_APPROVE: "INVOICE_APPROVE",
};
